### ISSUE TITLE
Lets see if I got this right...

### ISSUE THREAD

**Issue by paaljoachim** [NomadDevs/codex_creator#1]
I have a tutorial site http://easywebdesigntutorials.com/

If I wanted to create a documentation section for my tutorials I would be able to do so with this plugin....?

A doc page for sections - Getting Started using WordPress - Learning about plugins - SEO - Local Development - etc etc. Various sections to lead to either new custom codex creator posts or existing posts tutorials. A way to logically group my posts into sections making it easier for users to go to a section and find specific posts. Right now finding tutorials is somewhat messy.

Something similar to http://docs.wpgeodirectory.com/codex/ which looks pretty nice btw.

A good docs section with a good sidebar widget.

Is this correct?

**Comment by Stiofan** [comment]
I think you have misunderstood what this plugin does, it scans a plugin's files for docblock information and then creates documentaion from them. http://en.wikipedia.org/wiki/PHPDoc#DocBlock

**Comment by paaljoachim** [comment]
Thanks for the reply.
